name: Terraform CI/CD
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      working-directory:
        required: true
        type: string
      terraform-version:
        required: false
        type: string
        default: "1.7.0"
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_RG:
        required: true
      AKS_NAME:
        required: true
jobs:
  Terraform-plan:
    # Only run on PR request
    if: github.event_name == 'pull_request'
    # Set the environment
    environment: ${{ inputs.environment }}
    # Add permissions to connect to az
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    # Set defaults for all steps
    defaults:
      run:
        working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
    # Specifying the runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Debug list files
        run: |
          pwd
          ls -l ${{ github.workspace }}/${{ inputs.working-directory }}

      # Step 2: Log in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 3: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Step 4: Terraform init to build providers/modules
      - name: Terraform Init
        run: terraform init -reconfigure # new state
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      # Comment for PR to give feedback to usera
      - name: PR comment for Terraform init results
        if: github.event_name== 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "Terraform successfully initialised ✅"
      # Step 5: Trigger Terraform Plan
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -out=tfplan.binary
          terraform show -json tfplan.binary > tfplan.json
        env:
          TF_VAR_appId: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_password: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Upload the plan for the later apply job
      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ github.workspace }}/${{ inputs.working-directory }}/tfplan.binary
          retention-days: 1
      - name: Comment Terraform plan (Python fetcher)
        run: python3 -v ${{ github.workspace }}/.github/scripts/plan-pr-comment-fetch.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}

  # Apply job starts here
  Terraform-apply:
    if: github.ref == format('refs/heads/{0}', inputs.environment) && github.event_name == 'push'
    # Set the environment
    environment: ${{ inputs.environment }}
    # Add permissions to connect to az
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    # Set defaults for all steps
    defaults:
      run:
        working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 3: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      # Step 4: Terraform init to build providers/modules
      - name: Terraform Init
        run: terraform init
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      # Step 6: Apply the plan.
      - name: Terraform Apply
        run: terraform apply
      # Step 7: Get the server IP that is now running on AKS
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{ secrets.AZURE_RG }} --name ${{ secrets.AKS_NAME }} --overwrite-existing
      - name: Get MLflow external IP
        id: mlflow_ip
        run: echo "MLFLOW_EXTERNAL_IP=$(kubectl get svc mlflow -n ${{ secrets.AKS_NAMESPACE }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_OUTPUT

      - name: Show MLflow server address
        run: echo "MLflow deployment finished. cc @vulcanfox — http://${{ steps.mlflow_ip.outputs.MLFLOW_EXTERNAL_IP }}" >> $GITHUB_STEP_SUMMARY
