name: Terraform multi-environment workflow

on:
  push:
    branches:
      - main
    paths:
      - "environments/**"
      - "modules/**"
  pull_request:
    paths:
      - "environments/**"
      - "modules/**"

jobs:
  matrix-terraform:
    strategy:
      matrix:
        environment:
          - name: production
            directory: ./environments/production

    uses: ./.github/workflows/terraform-reuse-workflow.yaml
    with:
      environment: ${{ matrix.environment.name }}
      working-directory: ${{ matrix.environment.directory }}
      terraform-version: 1.7.0
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
