name: Terraform CI/CD
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      working-directory:
        required: true
        type: string
      terraform-version:
        required: false
        type: string
        default: "1.7.0"
      plan-label:
        required: true
        type: "string"
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_RG:
        required: true
      AKS_NAME:
        required: true
      AKS_NAMESPACE:
        required: true
      AZURE_STORAGE_ACCOUNT:
        required: true
      AZURE_STORAGE_KEY:
        required: true
jobs:
  Terraform-plan:
    # Only run on PR request
    if: github.event_name == 'pull_request'
    # Set the environment
    environment: ${{ inputs.environment }}
    # Add permissions to connect to az
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    # Set defaults for all steps
    defaults:
      run:
        working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
    # Specifying the runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Debug list files
        run: |
          pwd
          ls -l ${{ github.workspace }}/${{ inputs.working-directory }}
      - name: Environment confirm
        run: echo ${{ inputs.working-directory }}  ${{ inputs.environment }}
      ######################################################################
      # Our organisation doesnt allow deploys on fridays.
      - name: Check Friday
        id: friday_check
        continue-on-error: true
        run: |
          if [ "$(date +%u)" = "5" ]; then
            echo "ðŸš« It's Friday!"
            exit 1
          fi

      - name: PR comment for friday check
        if: github.event_name == 'pull_request' && steps.friday_check.outcome == 'failure'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: " ðŸ“…  It's Friday! No deploys allowed ðŸš«. Nobody wants the potential pain!"

      - name: PR comment for friday check
        if: github.event_name == 'pull_request' && steps.friday_check.outcome != 'failure'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "Today is not a Friday, so you can deploy! âœ…"

      - name: Fail if Friday
        if: steps.friday_check.outcome == 'failure'
        run: exit 1
      #####################################################################
      # Step 2: Log in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 3: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Step 4: Terraform init to build providers/modules
      - name: Terraform Init
        run: terraform init -reconfigure # new state
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      # Comment for PR to give feedback to usera
      - name: PR comment for Terraform init results
        if: github.event_name== 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "Terraform successfully initialised âœ…"
      # Step 5: Trigger Terraform Validate + Plan
      - name: Terraform Validate
        run: terraform validate
      # Terraform plan
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -out=tfplan.binary
          terraform show -json tfplan.binary > tfplan.json
        env:
          TF_VAR_appId: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_password: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_namespace: ${{secrets.AKS_NAMESPACE}}
          TF_VAR_generic_name: ${{secrets.AKS_NAME}}
          TF_VAR_subscription: ${{secrets.AZURE_SUBSCRIPTION_ID}}

      # Step 6: Install terraform compliance
      - name: Install terraform compliance for compliance check
        run: pip install terraform-compliance

      # Step 7: Run compliance check
      - name: Run organisational complaince check
        run: terraform-compliance -p tfplan.binary -f ${{ github.workspace }}/.github/policies/
      # Comment for PR to give feedback to usera
      - name: PR comment for Compliance check result
        if: github.event_name== 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "Compliance policies check passed âœ…"
      # Step 8: Upload to blob storage
      - name: Upload tfplan to Azure Blob
        run: |
          az storage blob upload \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --container-name terraform-plans \
            --name tfplan-${{ inputs.plan-label }}.binary \
            --file tfplan.binary \
            --overwrite true
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      - name: Comment Terraform plan (Python fetcher)
        run: python3 -v ${{ github.workspace }}/.github/scripts/plan-pr-comment-fetch.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}

  # Apply job starts here
  Terraform-apply:
    if: github.ref == format('refs/heads/{0}', inputs.environment) && github.event_name == 'push'
    # Set the environment
    environment: ${{ inputs.environment }}
    # Add permissions to connect to az
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    # Set defaults for all steps
    defaults:
      run:
        working-directory: ${{ github.workspace }}/${{ inputs.working-directory }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Log in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Step 3: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      # Step 4: Terraform init to build providers/modules
      - name: Terraform Init
        run: terraform init
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      - name: Verify blob uploaded
        run: |
          az storage blob list \
            --account-name  ${{secrets.AZURE_STORAGE_ACCOUNT}} \
            --account-key  ${{secrets.AZURE_STORAGE_KEY}} \
            --container-name terraform-plans \
            --output table

      # Step 5: Download the saved plan from the plan job previously
      - name: Download tfplan from Azure Blob
        run: |
          az storage blob download \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --container-name terraform-plans \
            --name tfplan-${{ inputs.plan-label }}.binary \
            --file tfplan.binary
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

      # Step 6: Apply the plan.
      - name: Terraform Apply
        run: terraform apply tfplan.binary
        env:
          TF_VAR_appId: ${{ secrets.AZURE_CLIENT_ID }}
          TF_VAR_password: ${{ secrets.AZURE_CLIENT_SECRET }}
          TF_VAR_namespace: ${{secrets.AKS_NAMESPACE}}
          TF_VAR_generic_name: ${{secrets.AKS_NAME}}
          TF_VAR_subscription: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      - name: Show created resource group
        run: |
          echo  ${{secrets.AKS_NAME}}-rg
          az group show --name  ${{secrets.AKS_NAME}}-rg --output table

      # Step 7: Get the server IP that is now running on AKS
      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group ${{secrets.AKS_NAME}}-rg --name ${{ secrets.AKS_NAME }}-cluster --overwrite-existing
      - name: Get MLflow external IP
        id: mlflow_ip
        run: echo "MLFLOW_EXTERNAL_IP=$(kubectl get svc mlflow -n ${{ secrets.AKS_NAMESPACE }} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_OUTPUT

      - name: Show MLflow server address
        run: echo "MLflow deployment finished. cc @vulcanfox â€” http://${{ steps.mlflow_ip.outputs.MLFLOW_EXTERNAL_IP }}" >> $GITHUB_STEP_SUMMARY
